# .readthedocs.yaml
version: 2

# Set the version of Python and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: pyrobosim
    - method: pip
      path: pyrobosim_ros

# Build documentation in the Sphinx source directory
sphinx:
  configuration: docs/source/conf.py
