# .readthedocs.yaml
version: 2

# Set the version of Python and other tools
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

# Ensure the ROS related submodules are included
submodules:
  include:
    - pyrobosim_ros
  recursive: true

python:
  install:
    - requirements: docs/python_docs_requirements.txt
    - method: pip
      path: pyrobosim
    - method: pip
      path: pyrobosim_ros/pyrobosim_ros

# Build documentation in the Sphinx source directory
sphinx:
  configuration: docs/source/conf.py
