services:
  pyrobosim-mcp:
    image: pyrobosim_ros:humble
    container_name: pyrobosim
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /Users/jonathansalfity/Documents/dev/pyrobosim:/workspace/pyrobosim
    ports:
      - "9000:9000"
      - "9001:9001"
    working_dir: /workspace/pyrobosim/pyrobosim
    command: >-
      bash -lc "python3 -m pip install -e . &&
      python3 -m pip install -U py_trees fastmcp &&
      python3 -m pyrobosim.mcp.sim_server --transport streamable-http --host 0.0.0.0 --port 9000"
    tty: true
    stdin_open: true
