# Execute Task Plan -- ROS Action Definition

# Goal
pyrobosim_msgs/TaskPlan plan

---

# Result
pyrobosim_msgs/ExecutionResult execution_result
int64 num_completed
int64 num_total

---

# No Feedback
