# Execute Task Action -- ROS Action Definition

# Goal

# The action to execute
pyrobosim_msgs/TaskAction action

# A multiplier on the execution time relative to real time.
# Defaults to 1.0. If negative, runs as quickly as possible.
float32 realtime_factor 1.0

---

# Result
pyrobosim_msgs/ExecutionResult execution_result

---

# No Feedback
