"""
Utlities to reduce the number of waypoints generated by a planner.
"""

import math

def reduce_waypoints(grid, poses):
    """
    Reduces the number of waypoints in the generated path

    :param grid: The occupancy grid associated with the generated path
    :type grid: :class:`pyrobosim.navigation.occupancy_grid.OccupancyGrid`
    :param poses: The list of of poses that make up the path
    :type poses: list[(int, int)]
    :return: The optimized list of waypoints
    :rtype: list[(int, int)]
    """
    waypoints = []
    start = poses[0]
    waypoints.append(start)
    poses = poses[1:]
    i = len(poses) - 1
    while poses and i >= 0:
        current = poses[i]
        if grid.connectable(start, current)[0]:
            waypoints.append(current)
            start = current
            poses = poses[i + 1 :]
            i = len(poses) - 1
        else:
            i -= 1
    return waypoints
